{
 "title": "Etcd",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "has a leader?",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "etcd_server_has_leader",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_url",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "url" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "etcd_debugging_mvcc_db_total_size_in_bytes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Receivced ($tag_url)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "url" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "etcd_network_client_grpc_received_bytes_total",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ]
    },
    {
     "alias": "Sent ($tag_url)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "url" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "etcd_network_client_grpc_sent_bytes_total",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Resident Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_url",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "url" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "process_resident_memory_bytes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "# instances",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "etcd_server_has_leader",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Put",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Started ($tag_url)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "url" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "grpc_server_started_total",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "grpc_type", "operator": "=", "value": "unary" },
      { "condition": "AND", "key": "grpc_method", "operator": "=", "value": "Put" }
     ]
    },
    {
     "alias": "Failed ($tag_url)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "url" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "grpc_server_handled_total",
     "query": "SELECT sum(\"value\") FROM \"grpc_server_handled_total\" WHERE (\"grpc_code\" != 'OK' AND \"grpc_type\" = 'unary' AND \"grpc_method\" = 'Put') AND $timeFilter GROUP BY time($__interval), \"url\" fill(null)",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "grpc_code", "operator": "!=", "value": "OK" },
      { "condition": "AND", "key": "grpc_type", "operator": "=", "value": "unary" },
      { "condition": "AND", "key": "grpc_method", "operator": "=", "value": "Put" }
     ]
    }
   ]
  },
  {
   "title": "Get/Range",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Started ($tag_url)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "url" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "grpc_server_started_total",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "grpc_type", "operator": "=", "value": "unary" },
      { "condition": "AND", "key": "grpc_method", "operator": "=", "value": "Range" }
     ]
    },
    {
     "alias": "Failed ($tag_url)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "url" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "grpc_server_handled_total",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "grpc_code", "operator": "!=", "value": "OK" },
      { "condition": "AND", "key": "grpc_type", "operator": "=", "value": "unary" },
      { "condition": "AND", "key": "grpc_method", "operator": "=", "value": "Range" }
     ]
    }
   ]
  },
  {
   "title": "gRpc  ops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Started ($tag_url)",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "url" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "grpc_server_started_total",
     "query": "SELECT derivative(mean(\"counter\"), 5m) FROM \"grpc_server_started_total\" WHERE (\"grpc_type\" = 'unary') AND $timeFilter GROUP BY time($__interval), \"url\" fill(null)",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ]
    },
    {
     "alias": "Failed ($tag_url)",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "url" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "grpc_server_handled_total",
     "query": "SELECT sum(\"counter\") FROM \"grpc_server_handled_total\" WHERE (\"grpc_type\" = 'unary' AND \"grpc_code\" != 'OK') AND $timeFilter GROUP BY time(10s), \"url\"",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "grpc_code", "operator": "!=", "value": "OK" }
     ]
    }
   ]
  },
  {
   "title": "Watch",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Started ($tag_url)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "url" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "grpc_server_started_total",
     "query": "SELECT non_negative_difference(mean(\"counter\")) FROM \"grpc_server_started_total\" WHERE (\"grpc_method\" = 'Watch') AND $timeFilter GROUP BY time($__interval), \"url\" fill(null)",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "grpc_method", "operator": "=", "value": "Watch" }
     ]
    },
    {
     "alias": "Failed ($tag_url)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "url" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "grpc_server_handled_total",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "grpc_code", "operator": "!=", "value": "OK" },
      { "condition": "AND", "key": "grpc_method", "operator": "=", "value": "Watch" }
     ]
    }
   ]
  }
 ]
}